server:
  port: 5000

spring:
  profiles:
    active: db

---
spring:
  profiles: db
  datasource:
    url: jdbc:h2:file:./numbers
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

---
spring:
  profiles: in-memory
